### ISSUE TITLE
Réclamation éventuelle

### ISSUE THREAD

**Issue by RemyK888** [aeziotech/discord-invite-logger#3]
Bonjour, peux-tu envoyer le lien de ton serveur Discord dédié s'il te plaît ?
Merci d'avance !!

**Comment by RemyK888** [comment]
@aeziotech

**Comment by aeziotech** [comment]
Oops, j'avais pas vu le message ^^
Le bot est maintenant mit à jour. Il utilise la dernière version de discord.js, avec les boutons.
L'invitation du serveur discord est à jour dans le readme.md
