### ISSUE TITLE
Je suis sûrement bête 😜 mais je ne trouve pas le fichier « .env ».

### ISSUE THREAD

**Issue by The-discord-cat** [aeziotech/discord-invite-logger#5]
Et oui 👍 je ne trouve pas le fichier « .env » et ne sais pas si il faut en crée un ou autre... DONC ... je ne sais pas ou mettre le token x)

**Comment by aeziotech** [comment]
Merci ! Je viens de modifier le readme. Il faut créer un nouveau fichier ".env" à la racine du projet, et mettre ton token comme indiqué sur le readme !
Bonne journée
