### ISSUE TITLE
TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.

### ISSUE THREAD

**Issue by Nyrok** [aeziotech/discord-invite-logger#6]
Je ne crois pas avoir fait d'erreur ayant bien créer le fichier dotenv et paramétré le token, l'erreur dit que je n'ai pas activé les intents pour le client sauf que je les ai bien activés du coup je me retrouve un peu paumé..

![](https://media.discordapp.net/attachments/804771716789960755/873937481874174002/unknown.png)

**Comment by Nyrok** [comment]
Après multiples tests, l'erreur survient avec la V13 de Discord.js, j'ai testé sur un nouveau dossier avec seulement cette version d'installée et j'ai eu cette erreur.
Root :
![](https://media.discordapp.net/attachments/804771716789960755/873944613453455400/unknown.png)
Code : 
![](https://media.discordapp.net/attachments/804771716789960755/873944876444684318/unknown.png)
Donc je ne pense pas qu'on puisse faire grand chose pour le moment à part peut être installer [ce module npm](https://www.npmjs.com/package/discord-buttons) qui remplace l'implémentation des boutons de la V13.

**Comment by royaljacques** [comment]
hey pour vous répondre , liser l'erreur CLIENT_MISSING_INTENTS ce qui veut dire intent pas valide 
```js
const client = new Client({ intents: 32767 });```rajouter ce code dans le fichier index ( modif pluto )

**Comment by aeziotech** [comment]
Le module a été mis à jour ! Profitez bien !
