### ISSUE TITLE
Sa me dis token invalid

### ISSUE THREAD

**Issue by WorkiLaMenace** [aeziotech/discord-invite-logger#8]
j'ai suivi les instructions a la lettre et sa me met cette erreur 

PS C:\Users\worki\Desktop\InviteLoggerDiscordBot-main> node .\src\index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)                                       ed.
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)                             rc\client\Client.js:206:52)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:39648) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise 
which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39648) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the fu either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catture, promise rejections that are not handled will terminate the Node.js process with a non-zero -rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
exit code.

**Comment by royaljacques** [comment]
je ne crois pas que ce soit un token invalide . tente de réinstaller le moduke en entier ( suprime le package.lock.json) pour voir sinon refair l'installation

**Comment by aeziotech** [comment]
Hello ! Désolé ! Je n'avais pas vu ton message... J'ai refais les modules pour que ça fonctionne. Profite-bien !
