### ISSUE TITLE
Left count

### ISSUE THREAD

**Issue by PantemEt2005** [aeziotech/discord-invite-logger#9]
How can i fix the left count not have minus[](url
![Screenshot_19](https://user-images.githubusercontent.com/28214152/148651921-2604b4c7-b023-4730-8758-4512c05523ec.png))

**Comment by aeziotech** [comment]
Try to edit that in the invites command file.
Don't forget to edit that too in the info command file.
That is not an error. Personnaly, i prefer to have the real count instead of the absolute value !
